### ISSUE TITLE
Use as a node module

### ISSUE THREAD

**Issue by sacOO7** [MegaGM/inject-handlebars#1]
Can I use this library as a node module? I needed it in one of my project :+1: . Thank you :)

**Comment by MegaGM** [comment]
You can, but, just in case, please consider, if you use Webpack, it's much easier to simply add https://github.com/pcardune/handlebars-loader to your config.

And what about this lib, I'd like to make some changes to it first. When I have been refactoring it, in March 2017, I made some breaking changes and (I'm not sure but apparently) I've dropped support for exporting every template, helper, partial as individual files. So it's only possible to output a single bundle file now. Is it okay with you?

I'm gonna rewrite Readme soon btw.

**Comment by sacOO7** [comment]
Are you going to rewrite it? Thank you very much !!!! Waiting for latest release... I will try to use the current version. Thank you once again :+1:

**Comment by MegaGM** [comment]
@sacOO7 I'm sorry for the delayed response. I made some changes: https://github.com/MegaGM/ya-handlebars-bundler/commit/5c185781081420d3fc6f7eff097f6193d48df5ac
Did you try to use the lib?

**Comment by MegaGM** [comment]
Since I've added usage examples as node module to Readme ages ago, I guess it's safe to close the issue.
